/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/NotFound'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as MoviesIdRouteImport } from './routes/movies/$id'
import { Route as MoviesUpcomingIndexRouteImport } from './routes/movies/upcoming/index'
import { Route as MoviesTopRatedIndexRouteImport } from './routes/movies/top-rated/index'
import { Route as MoviesPopularIndexRouteImport } from './routes/movies/popular/index'
import { Route as MoviesPlayerIdRouteImport } from './routes/movies/player/$id'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/NotFound',
  path: '/NotFound',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesUpcomingIndexRoute = MoviesUpcomingIndexRouteImport.update({
  id: '/movies/upcoming/',
  path: '/movies/upcoming/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesTopRatedIndexRoute = MoviesTopRatedIndexRouteImport.update({
  id: '/movies/top-rated/',
  path: '/movies/top-rated/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesPopularIndexRoute = MoviesPopularIndexRouteImport.update({
  id: '/movies/popular/',
  path: '/movies/popular/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesPlayerIdRoute = MoviesPlayerIdRouteImport.update({
  id: '/movies/player/$id',
  path: '/movies/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/NotFound': typeof NotFoundRoute
  '/movies/$id': typeof MoviesIdRoute
  '/about/': typeof AboutIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/movies/player/$id': typeof MoviesPlayerIdRoute
  '/movies/popular/': typeof MoviesPopularIndexRoute
  '/movies/top-rated/': typeof MoviesTopRatedIndexRoute
  '/movies/upcoming/': typeof MoviesUpcomingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/NotFound': typeof NotFoundRoute
  '/movies/$id': typeof MoviesIdRoute
  '/about': typeof AboutIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/movies/player/$id': typeof MoviesPlayerIdRoute
  '/movies/popular': typeof MoviesPopularIndexRoute
  '/movies/top-rated': typeof MoviesTopRatedIndexRoute
  '/movies/upcoming': typeof MoviesUpcomingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/NotFound': typeof NotFoundRoute
  '/movies/$id': typeof MoviesIdRoute
  '/about/': typeof AboutIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/movies/player/$id': typeof MoviesPlayerIdRoute
  '/movies/popular/': typeof MoviesPopularIndexRoute
  '/movies/top-rated/': typeof MoviesTopRatedIndexRoute
  '/movies/upcoming/': typeof MoviesUpcomingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/NotFound'
    | '/movies/$id'
    | '/about/'
    | '/movies/'
    | '/products/'
    | '/movies/player/$id'
    | '/movies/popular/'
    | '/movies/top-rated/'
    | '/movies/upcoming/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/NotFound'
    | '/movies/$id'
    | '/about'
    | '/movies'
    | '/products'
    | '/movies/player/$id'
    | '/movies/popular'
    | '/movies/top-rated'
    | '/movies/upcoming'
  id:
    | '__root__'
    | '/'
    | '/NotFound'
    | '/movies/$id'
    | '/about/'
    | '/movies/'
    | '/products/'
    | '/movies/player/$id'
    | '/movies/popular/'
    | '/movies/top-rated/'
    | '/movies/upcoming/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  MoviesIdRoute: typeof MoviesIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  MoviesPlayerIdRoute: typeof MoviesPlayerIdRoute
  MoviesPopularIndexRoute: typeof MoviesPopularIndexRoute
  MoviesTopRatedIndexRoute: typeof MoviesTopRatedIndexRoute
  MoviesUpcomingIndexRoute: typeof MoviesUpcomingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/NotFound': {
      id: '/NotFound'
      path: '/NotFound'
      fullPath: '/NotFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/upcoming/': {
      id: '/movies/upcoming/'
      path: '/movies/upcoming'
      fullPath: '/movies/upcoming/'
      preLoaderRoute: typeof MoviesUpcomingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/top-rated/': {
      id: '/movies/top-rated/'
      path: '/movies/top-rated'
      fullPath: '/movies/top-rated/'
      preLoaderRoute: typeof MoviesTopRatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/popular/': {
      id: '/movies/popular/'
      path: '/movies/popular'
      fullPath: '/movies/popular/'
      preLoaderRoute: typeof MoviesPopularIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/player/$id': {
      id: '/movies/player/$id'
      path: '/movies/player/$id'
      fullPath: '/movies/player/$id'
      preLoaderRoute: typeof MoviesPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  MoviesIdRoute: MoviesIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  MoviesPlayerIdRoute: MoviesPlayerIdRoute,
  MoviesPopularIndexRoute: MoviesPopularIndexRoute,
  MoviesTopRatedIndexRoute: MoviesTopRatedIndexRoute,
  MoviesUpcomingIndexRoute: MoviesUpcomingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
